#!/usr/bin/env python3

class ttsManager:
    "text to speak manager"
    def set_text(self,text):
        self.text = text
        
    def __init__(self,text):
        self.set_text(text)

class ftsManager:
    "file to speak manager"

    file     = None
    filename = None
    text     = None
    def read_file(self):
        self.file = fopen(self.filename,'r')
        if self.is_valid():
            self.text = ttsManager()

    def is_valid(self):
        return self.file.readable()

    def set_filename(self,filename):
        self.filename = filename
        
    def __init__(self,filename):
        self.set_filename(filename)
        self.read_file()

class SpeakIt:

    def __init__(self):
