#!/usr/bin/env python3
from optparse import OptionParser

class argsManager:

    parser = OptionParser()
    filename = None
    outfilename = None
    text     = None

    def __setup_opts__(self):
        
        self.parser.add_option("-f", "--file", dest="filename",
                        help="choisir le fichier a lire", metavar="FILE")

        self.parser.add_option("-o", "--outfile", dest="outfilename",
                        help="enregistrer dans le fichier", metavar="FILE")

        self.parser.add_option("-t", "--text", dest="filename",
                        help="specifier le texte a lire")

    def __set_opts__(self):
        (options, args) = parser.parse_args()
        for option in options:
            self._set(option,options[option])

    def gotopt(self,optname):
        return optname in self

    def _set(self,optname,optval):
        self[optname] = optval

    def get(self,optname):
        return self[optname] if self.gotopt(optname) else None

    def __init__(self):
        self.__setup_opts__()
        self.__set_opts()



class ttsManager:
    "text to speak manager"
    lines = []
    text  = None
    def set_lines(self,lines):
        self.lines = lines

    def set_text(self,text=None):
        self.text = text  if text else ''.join(self.lines)
        
    def get_lines(self):
        return self.lines
        
    def get_text(self):
        return self.text

    def __init__(self,lines):
        self.set_lines(lines)
        self.set_text()

class ftsManager:
    "file to speak manager"

    file     = None
    filename = None
    text     = None

    def get_text(self):
        return self.text.get_text() if self.text else ""

    def get_lines(self):
        return self.text.get_lines() if self.text else []

    def read_file(self):
        self.file = fopen(self.filename,'r')
        if self.is_valid():
            self.text = ttsManager(self.file.readlines())
        self.file.close()

    def is_valid(self):
        return self.file.readable()

    def set_filename(self,filename):
        self.filename = filename
        
    def __init__(self,filename):
        self.set_filename(filename)
        self.read_file()

class SpeakIt:

    def __run__(self):
        "just run and exit"

    def __interact__(self):
        "interact"

    def check_args():
        return self.args.get('filename') or self.args.get('text')

    def __init__(self):
        self.args = argsManager()
        if self.check_args():
            self.__run__()
        else:
            self.__interact__()

